### ISSUE TITLE
Fix CI for forks

### ISSUE THREAD

**Issue by tfalencar** [spruceid/siwe#113]
Please see build: https://github.com/tfalencar/siwe/runs/8131455272?check_suite_focus=true#step:4:228 

```
Error: invalid signature string (argument="signature", value="0x2f280385ebd550309197c4c892c5a8eb1a6e743d5c90c8036dea6f05c3e8cb321f90210a567ee88461733731a9c4e177140a969784c0421c09897e161f17bf331c02", code=INVALID_ARGUMENT, version=bytes/5.7.0)
[148](https://github.com/tfalencar/siwe/runs/8131455272?check_suite_focus=true#step:4:149)
          at Logger.Object.<anonymous>.Logger.makeError (/home/runner/work/siwe/siwe/packages/siwe/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
[149](https://github.com/tfalencar/siwe/runs/8131455272?check_suite_focus=true#step:4:150)
          at Logger.Object.<anonymous>.Logger.throwError (/home/runner/work/siwe/siwe/packages/siwe/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
[150](https://github.com/tfalencar/siwe/runs/8131455272?check_suite_focus=true#step:4:151)
          at Logger.Object.<anonymous>.Logger.throwArgumentError (/home/runner/work/siwe/siwe/packages/siwe/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
[151](https://github.com/tfalencar/siwe/runs/8131455272?check_suite_focus=true#step:4:152)
          at splitSignature (/home/runner/work/siwe/siwe/packages/siwe/node_modules/@ethersproject/bytes/src.ts/index.ts:363:20)
[152](https://github.com/tfalencar/siwe/runs/8131455272?check_suite_focus=true#step:4:153)
          at recoverPublicKey (/home/runner/work/siwe/siwe/packages/siwe/node_modules/@ethersproject/signing-key/src.ts/index.ts:80:31)
[153](https://github.com/tfalencar/siwe/runs/8131455272?check_suite_focus=true#step:4:154)
          at recoverAddress (/home/runner/work/siwe/siwe/packages/siwe/node_modules/@ethersproject/transactions/src.ts/index.ts:115:43)
[154](https://github.com/tfalencar/siwe/runs/8131455272?check_suite_focus=true#step:4:155)
          at Object.verifyMessage (/home/runner/work/siwe/siwe/packages/siwe/node_modules/@ethersproject/wallet/src.ts/index.ts:197:26)
[155](https://github.com/tfalencar/siwe/runs/8131455272?check_suite_focus=true#step:4:156)
          at /home/runner/work/siwe/siwe/packages/siwe/lib/client.ts:307:22
[156](https://github.com/tfalencar/siwe/runs/8131455272?check_suite_focus=true#step:4:157)
          at new Promise (<anonymous>)
[157](https://github.com/tfalencar/siwe/runs/8131455272?check_suite_focus=true#step:4:158)
          at SiweMessage.<anonymous> (/home/runner/work/siwe/siwe/packages/siwe/lib/client.ts:206:12) {
[158](https://github.com/tfalencar/siwe/runs/8131455272?check_suite_focus=true#step:4:159)
        reason: 'invalid signature string',
```

**Comment by tfalencar** [comment]
The following tests seems to be failing: 

<img width="791" alt="Screenshot 2022-09-01 at 11 44 13" src="https://user-images.githubusercontent.com/4054009/187884624-f28fae3c-eb76-47a7-a8c3-2fa2693a3114.png">

Error: Error: signature missing v and recoveryParam (argument="signature", value="0xf2e8420fc1b722bf4941f5a0464f98172a758ceda5039f622e425fb69fd19b20e444bba7c9a8a8d7e2b5e453553efe7c9460be5d211abe473fc146d51bb04d0cb1b", code=INVALID_ARGUMENT, version=bytes/5.7.0) 

Then there are other messages, but I'm not sure if they are expected or not:

<img width="1203" alt="Screenshot 2022-09-01 at 11 50 00" src="https://user-images.githubusercontent.com/4054009/187885733-927f9754-0c83-4909-8b40-3ca045053257.png">

**Comment by sbihel** [comment]
The log line you pasted is not a test failure. If that `console.error` is a nuisance please open another issue.

**Comment by tfalencar** [comment]
The build I mentioned in the ticket description shows the following:

2022-09-01T09:03:15.7067387Z Test Suites: 1 failed, 1 passed, 2 total
2022-09-01T09:03:15.7067900Z Tests:       2 failed, 207 passed, 209 total

So I guess, *something* failed? Would you be able to tell from the logs?
