### ISSUE TITLE
Using siwe message giving me error "Buffer is not defined"

### ISSUE THREAD

**Issue by harshmittal1750** [spruceid/siwe#168]
```
Compiled with problems:
×
ERROR
Buffer is not defined
ReferenceError: Buffer is not defined
    at new api (http://localhost:3000/static/js/bundle.js:143342:3)
    at GrammarApi.generateApi (http://localhost:3000/static/js/bundle.js:140238:17)
    at ./node_modules/@spruceid/siwe-parser/dist/abnf.js (http://localhost:3000/static/js/bundle.js:140250:28)
    at options.factory (http://localhost:3000/static/js/bundle.js:246460:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:245849:33)
    at fn (http://localhost:3000/static/js/bundle.js:246117:21)
    at ./node_modules/@spruceid/siwe-parser/dist/parsers.js (http://localhost:3000/static/js/bundle.js:140407:16)
    at options.factory (http://localhost:3000/static/js/bundle.js:246460:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:245849:33)
    at fn (http://localhost:3000/static/js/bundle.js:246117:21)
```

**Comment by harshmittal1750** [comment]
I am using a nodejs env as backend into my react-typescript frontend

**Comment by harshmittal1750** [comment]
I have resloved this error , i was using createSiweMessage it in frontend , so using it as an backend solves this issue.
