### ISSUE TITLE
Installation Error on Windows 10

### ISSUE THREAD

**Issue by ice09** [spruceid/siwe#17]
On Windows 10, Node v15.6.0 with `npm install` in examples/notepad I get

```
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/home/hal9000/.nvm/versions/node/v15.6.0/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /home/hal9000/.nvm/versions/node/v15.6.0/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/home/hal9000/.nvm/versions/node/v15.6.0/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /home/hal9000/.nvm/versions/node/v15.6.0/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/home/hal9000/.nvm/versions/node/v15.6.0/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /home/hal9000/.nvm/versions/node/v15.6.0/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /home/hal9000/.nvm/versions/node/v15.6.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/hal9000/.nvm/versions/node/v15.6.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.4.72-microsoft-standard-WSL2
npm ERR! gyp ERR! command "/home/hal9000/.nvm/versions/node/v15.6.0/bin/node" "/home/hal9000/.nvm/versions/node/v15.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /mnt/c/dev/dlt/ethereum/signin-with-ethereum/siwe/examples/notepad/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v15.6.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
```

If I run `npm run dev` anyways, I get

```

> siwe-notepad-example@1.0.0 dev
> npm i --prefix ../../ && tsc -p ../../tsconfig.json && concurrently "nodemon src/index.ts --ignore public/ --ignore db/ --ignore build/" "webpack --watch"


up to date, audited 391 packages in 1s

55 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
sh: 1: concurrently: not found
```

**Comment by w4ll3** [comment]
Hi there, from your logs it seems you are running from a WSL2 shell, please run `sudo apt install build-essential make`. `npm ERR! gyp ERR! stack Error: not found: make` says `make` is missing, which seems to be necessary to build some dependency, `build-essential` package contains all necessary dependencies to build any C program, that's why you might need to install those.

**Comment by ice09** [comment]
Yes, indeed, that was the problem, thanks.
